"""feat: add circuit breaker failure_count to webhooks

Revision ID: 0fcd74dd860a
Revises: d315d931966f
Create Date: 2026-03-13 10:18:59.442956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fcd74dd860a'
down_revision = 'd315d931966f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failure_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('failure_count')

    # ### end Alembic commands ###
