"""cleanup: schemas and models

Revision ID: 3a1949f6e948
Revises: 7027ef4bdd87
Create Date: 2026-03-17 11:49:27.599925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1949f6e948'
down_revision = '7027ef4bdd87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', name='order_status_enum'),
               existing_nullable=False,
               postgresql_using='status::order_status_enum')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_url_event'), type_='unique')
        batch_op.create_unique_constraint('uq_user_url', ['user_id', 'target_url'])
        batch_op.drop_column('event_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uq_user_url', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_url_event'), ['user_id', 'target_url', 'event_type'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', name='order_status_enum'),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
