"""fix: webhook json array and order amount

Revision ID: 7027ef4bdd87
Revises: bbe16f6333c6
Create Date: 2026-03-16 12:01:40.671682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7027ef4bdd87'
down_revision = 'bbe16f6333c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_types', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('event_types')

    # ### end Alembic commands ###
