"""fix: order schema

Revision ID: bbe16f6333c6
Revises: c6bb12e48eae
Create Date: 2026-03-16 11:15:51.011028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbe16f6333c6'
down_revision = 'c6bb12e48eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('subtotal')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status_enum'),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('orders_user_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('orders_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status_enum'),
               nullable=False)
        batch_op.drop_column('total_amount')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
