"""feat: add dead letter queue table and endpoints

Revision ID: c6bb12e48eae
Revises: 0fcd74dd860a
Create Date: 2026-03-13 10:25:27.874350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bb12e48eae'
down_revision = '0fcd74dd860a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_dlq',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('webhook_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhook_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_dlq')
    # ### end Alembic commands ###
