"""feat: add idempotency key to orders for duplicate prevention

Revision ID: d315d931966f
Revises: 7c6600e8aa90
Create Date: 2026-03-13 10:15:10.614403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd315d931966f'
down_revision = '7c6600e8aa90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['idempotency_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
