"""feat: add webhook subscription model

Revision ID: f9ad03701022
Revises: ff8e7494c8d3
Create Date: 2026-03-11 12:29:28.297090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ad03701022'
down_revision = 'ff8e7494c8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status_enum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status_enum'),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
